//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HashService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method to decode a string using a hash key.
        /// </summary>
        internal static string K2_Decode_Method_Description {
            get {
                return ResourceManager.GetString("K2_Decode_Method_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        internal static string K2_Decode_Method_DisplayName {
            get {
                return ResourceManager.GetString("K2_Decode_Method_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        internal static string K2_Decode_Method_Name {
            get {
                return ResourceManager.GetString("K2_Decode_Method_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method to decode a string using a hash key.
        /// </summary>
        internal static string K2_Decode_ServiceObject_Description {
            get {
                return ResourceManager.GetString("K2_Decode_ServiceObject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        internal static string K2_Decode_ServiceObject_DisplayName {
            get {
                return ResourceManager.GetString("K2_Decode_ServiceObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        internal static string K2_Decode_ServiceObject_Name {
            get {
                return ResourceManager.GetString("K2_Decode_ServiceObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceObject to encdoe and decode using a hash key.
        /// </summary>
        internal static string K2_Description {
            get {
                return ResourceManager.GetString("K2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Service.
        /// </summary>
        internal static string K2_DisplayName {
            get {
                return ResourceManager.GetString("K2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method to encode a string using a hash key.
        /// </summary>
        internal static string K2_Encode_Method_Description {
            get {
                return ResourceManager.GetString("K2_Encode_Method_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        internal static string K2_Encode_Method_DisplayName {
            get {
                return ResourceManager.GetString("K2_Encode_Method_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        internal static string K2_Encode_Method_Name {
            get {
                return ResourceManager.GetString("K2_Encode_Method_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method to encode a string using a hash key.
        /// </summary>
        internal static string K2_Encode_ServiceObject_Description {
            get {
                return ResourceManager.GetString("K2_Encode_ServiceObject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        internal static string K2_Encode_ServiceObject_DisplayName {
            get {
                return ResourceManager.GetString("K2_Encode_ServiceObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        internal static string K2_Encode_ServiceObject_Name {
            get {
                return ResourceManager.GetString("K2_Encode_ServiceObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashService.
        /// </summary>
        internal static string K2_Name {
            get {
                return ResourceManager.GetString("K2_Name", resourceCulture);
            }
        }
    }
}
